events { worker_connections 1024; }

http {
    upstream backend  { server server:3000; }
    upstream frontend { server client:80;   }

    server {
        listen 80;
        client_max_body_size 10M;

    
        location /api/ {
            proxy_pass       http://backend;
            proxy_set_header Host            $host;
            proxy_set_header X-Real-IP       $remote_addr;
            proxy_read_timeout 60s;
        }

       
        location / {
            proxy_pass       http://frontend;
            proxy_set_header Host            $host;
        }
    }
}